name: Deploy to github pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: commit files
        run: |
          rm -rf docs/guide/**/*
          rm -rf docs/design/**/*
          mdbook build design
          mdbook build guide
          git config --local user.name "Deploy Action"
          git config --local user.email "dev@example.com"
          echo "FIXME: Ignoring the output of git commit and git push"
          git checkout master
          git pull
          git commit -m "auto build documentation for commit ${{ github.sha }}" -a || true
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: .
          TARGET_FOLDER: .
