name: Deploy to github pages

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:

      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Removing old guide
        run: rm -rf docs/guide/**/*
      - name: Removing old design guide
        run: rm -rf docs/design/**/*
      - run: mdbook build design
      - run: mdbook build guide
      - name: commit files
        run: |
          git config --local user.name "Deploy Action"
          git config --local user.email "dev@example.com"
          git commit -m "auto build documentation for commit ${{ github.sha }}" -a ||
          echo "FIXME: Ignoring the output of git commit and git push --force"
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: .
          TARGET_FOLDER: .
