name: Slash Command Dispatch
on:
  issue_comment:
    types: [created, edited]
jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Rebase
        if: github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@master
        - name: Automatic Rebase
          uses: cirrus-actions/rebase@1.2
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commands: deploy, release, initialize
