name: pull request linter

on:
  pull_request

jobs:
  delivery:

    runs-on: ubuntu-latest

    steps:
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkDocsLabel
      with:
        label: docs
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkDesignLabel
      with:
        label: design
    - uses: Dreamcodeio/pr-has-label-action@master
      id: checkProgrammingLabel
      with:
        label: programming
    - name: Does 'pull_request' has ${{ steps.checkLabel.outputs.checkedLabel }} label?
      run: echo "${{ steps.checkLabel.outputs.hasLabel }}"
    - name: Check out code
      uses: actions/checkout@master
    - name: Run mdl
      uses: actionshub/markdownlint@master
    - name: Lint VN project
      uses: ProjectAliceDev/renpy-lint-action@master
      env:
        SDL_AUDIODRIVER: dummy
        SDL_VIDEODRIVER: dummy
