on:
  repository_dispatch:
    types: [release-command]

jobs:
  check_init_command:
    name: run release command
    runs-on: ubuntu-18.04
    steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Build renpy project
          uses: ProjectAliceDev/renpy-build-action@master
          with:
            project-dir: '.'
          env:
            SDL_AUDIODRIVER: dummy
            SDL_VIDEODRIVER: dummy
        - run: |
            mv renpy-dists/renplate-pc.zip renplate-pc.zip
            mv renpy-dists/renplate-win.zip renplate-win.zip
            mv renpy-dists/renplate-mac.zip renplate-mac.zip
            mv renpy-dists/renplate-linux.tar.bz2 renplate-linux.tar.bz2
            mv renpy-dists/renplate-web.zip renplate-web.zip

        - uses: "marvinpinto/action-automatic-releases@latest"
          if: github.event.client_payload.slash_command.args == ''
          with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development Build"
             files: |
               renplate-pc.zip
               renplate-win.zip
               renplate-mac.zip
               renplate-linux.tar.bz2
               renplate-web.zip

        - uses: "marvinpinto/action-automatic-releases@latest"
          if: github.event.client_payload.slash_command.args != ''
          with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "${{ github.event.client_payload.slash_command.args }}"
             prerelease: false
             title: "Development Build"
             files: |
               renplate-pc.zip
               renplate-win.zip
               renplate-mac.zip
               renplate-linux.tar.bz2
               renplate-web.zip
