on: issue_comment
name: Issue Comments
jobs:
  check_comments:
    name: Check comments for /test
    runs-on: ubuntu-18.04
    steps:
        - name: Check for Command
          id: releaseCommand
          uses: xt0rted/slash-command-action@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            command: release
            reaction: "true"
            reaction-type: "eyes"
            allow-edits: "false"
            permission-level: admin
        - name: Check out code
          uses: actions/checkout@master
        - name: Build renpy project
          uses: ProjectAliceDev/renpy-build-action@master
          with:
            project-dir: '.'
          env:
            SDL_AUDIODRIVER: dummy
            SDL_VIDEODRIVER: dummy
        - run: |
            mkdir BuildArtifacts
            cp renplate-*-dists/renplate-*-linux.tar.bz2 renplate-linux.tar.bz2
            cp renplate-*-dists/renplate-*-mac.zip renplate-mac.zip
            cp renplate-*-dists/renplate-*-pc.zip renplate-pc.zip

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development Build"
             files: |
               renplate-pc.zip
               renplate-mac.zip
               renplate-linux.tar.bz2
        - name: Reply to comment
          uses: actions/github@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: comment "🎉 New development release pushed"

        - name: Check for Command
          id: releaseDocsCommand
          uses: xt0rted/slash-command-action@v1
          with:
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            command: release-docs
            reaction: "true"
            reaction-type: "eyes"
            allow-edits: "false"
            permission-level: admin
        - name: Check out code
          uses: actions/checkout@master
        - run: |
            echo "FIXME: Ignoring the output of git commit and git push"
            git checkout master
            git pull
            rm -rf docs/guide/**/*
            rm -rf docs/design/**/*
            mdbook build design
            mdbook build guide
            git config --local user.name "Deploy Action"
            git config --local user.email "dev@example.com"
            git commit -m "auto build documentation for commit ${{ github.sha }}" -a || true

        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.ACCESS_TOKEN }}

        - name: Reply to comment
          uses: actions/github@v1.0.0
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: comment "🎉 New documentation release pushed"
