on:
  repository_dispatch:
    types: [release-command]

jobs:
  check_init_command:
    name: run release command
    runs-on: ubuntu-18.04
    steps:
        - name: Check out code
          uses: actions/checkout@master
        - name: Build renpy project
          uses: ProjectAliceDev/renpy-build-action@master
          with:
            project-dir: '.'
          env:
            SDL_AUDIODRIVER: dummy
            SDL_VIDEODRIVER: dummy
        - run: |
            ls -lsa

        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
             repo_token: "${{ secrets.GITHUB_TOKEN }}"
             automatic_release_tag: "latest"
             prerelease: true
             title: "Development Build"
             files: |
               renplate-pc.zip
               renplate-mac.zip
               renplate-linux.tar.bz2
